{
  ***************************************************
  * Este código é gerado automaticamente, não edite *
  ***************************************************

  Template: VisaoHTML.pas_template
  Descrição: Cria uma visão (geração de HTML) a partir do arquivo CreditBr_Visao_Pagina_Mestra.html
}

unit CreditBr_Visao_Pagina_Mestra;

interface

uses
  SysUtils, Classes, Variants, ServiceLocator, HTTPApp, MVC_Interfaces, MVC_Visao_HTML, 
  MVC_Visao_HTML_ActiveRecord;

type
  TVisaoPaginaMestra = class(TVisaoHTMLActiveRecord)
  private
  protected
    procedure ProcessaVisao; override;
    function ItemDoMenu(const ARotaFluente: IRotaFluente; const ACaption: string): IHTMLFluente; overload;
    function ItemDoMenu(const ARotaFluente: IRotaFluente; const AHTMLPuro: THTMLPuro): IHTMLFluente; overload;
  end;

implementation

{ TVisaoPaginaMestra }

procedure TVisaoPaginaMestra.ProcessaVisao;
begin  
  Response.SetCustomHeader('X-UA-Compatible', 'IE=edge,chrome=1'); 
; WriteLn('<!DOCTYPE html>');
WriteLn('<html lang="pt-BR">');
WriteLn('	<head>');
WriteLn('		<meta charset="Windows-1252">');
WriteLn('		<meta name="viewport" content="width=device-width, initial-scale=1">');
WriteLn('		<!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->');
WriteLn('');
WriteLn('		<meta name="description" content="Sistema de apoio da Credit Brasil">');
WriteLn('		<meta name="author" content="Credit Brasil">');
Write  ('		<link rel="apple-touch-icon" sizes="76x76" href="'); WriteVl(NovaRota.Nome('Padrao').Controlador('Tema').Acao('icones').Outros(['apple-icon-76x76.png'])); WriteLn('">');
Write  ('		<link rel="apple-touch-icon" sizes="72x72" href="'); WriteVl(NovaRota.Nome('Padrao').Controlador('Tema').Acao('icones').Outros(['apple-icon-72x72.png'])); WriteLn('">');
Write  ('		<link rel="apple-touch-icon" sizes="60x60" href="'); WriteVl(NovaRota.Nome('Padrao').Controlador('Tema').Acao('icones').Outros(['apple-icon-60x60.png'])); WriteLn('">');
Write  ('		<link rel="apple-touch-icon" sizes="57x57" href="'); WriteVl(NovaRota.Nome('Padrao').Controlador('Tema').Acao('icones').Outros(['apple-icon-57x57.png'])); WriteLn('">');
Write  ('		<link rel="icon" type="image/png" sizes="72x72" href="'); WriteVl(NovaRota.Nome('Padrao').Controlador('Tema').Acao('icones').Outros(['android-icon-72x72.png'])); WriteLn('">');
Write  ('		<link rel="icon" type="image/png" sizes="48x48" href="'); WriteVl(NovaRota.Nome('Padrao').Controlador('Tema').Acao('icones').Outros(['android-icon-48x48.png'])); WriteLn('">');
Write  ('		<link rel="icon" type="image/png" sizes="36x36" href="'); WriteVl(NovaRota.Nome('Padrao').Controlador('Tema').Acao('icones').Outros(['android-icon-36x36.png'])); WriteLn('">');
Write  ('		<link rel="icon" type="image/png" sizes="32x32" href="'); WriteVl(NovaRota.Nome('Padrao').Controlador('Tema').Acao('icones').Outros(['favicon-32x32.png'])); WriteLn('">');
Write  ('		<link rel="icon" type="image/png" sizes="96x96" href="'); WriteVl(NovaRota.Nome('Padrao').Controlador('Tema').Acao('icones').Outros(['favicon-96x96.png'])); WriteLn('">');
Write  ('		<link rel="icon" type="image/png" sizes="16x16" href="'); WriteVl(NovaRota.Nome('Padrao').Controlador('Tema').Acao('icones').Outros(['favicon-16x16.png'])); WriteLn('">');
Write  ('		<link rel="icon" href="'); WriteVl(NovaRota.Nome('Padrao').Controlador('Tema').Acao('icones').Outros(['favicon.ico'])); WriteLn('">');
WriteLn('');
Write  ('		<title>'); WriteVl(GetTitulo); WriteLn('</title>');
WriteLn('');
Write  ('		'); WriteVl(TemaCSS('bootstrap')); WriteLn('');
Write  ('		'); WriteVl(TemaCSS('metisMenu')); WriteLn('');
Write  ('		'); WriteVl(TemaCSS('sb-admin-2')); WriteLn('');
Write  ('		'); WriteVl(TemaCSS('font-awesome')); WriteLn('');
WriteLn('');
WriteLn('		<!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->');
WriteLn('		<!--[if lt IE 9]>');
WriteLn('			<script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>');
WriteLn('			<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>');
WriteLn('		<![endif]-->');
WriteLn('	</head>');
WriteLn('');
WriteLn('	<body>');
WriteLn('		<div id="wrapper">');
WriteLn('');
WriteLn('				<!-- Navigation -->');
WriteLn('				<nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0">');
WriteLn('						<div class="navbar-header">');
WriteLn('								<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">');
WriteLn('										<span class="sr-only">Abre a navegação</span>');
WriteLn('										<span class="icon-bar"></span>');
WriteLn('										<span class="icon-bar"></span>');
WriteLn('										<span class="icon-bar"></span>');
WriteLn('								</button>');
Write  ('								'); WriteVl(Acao(NovaRota.Nome('Padrao').Controlador('Principal'), HTMLPuro('<img src="' + NovaRota.Nome('Padrao').Controlador('Tema').Acao('imagens').Outros(['logo.png']).URL + '">')).AddClasse('navbar-brand')); WriteLn('');
WriteLn('						</div>');
WriteLn('						<!-- /.navbar-header -->');
WriteLn('');
WriteLn('						<ul class="nav navbar-top-links navbar-right">');
WriteLn('								<!--li class="dropdown">');
WriteLn('										<a class="dropdown-toggle" data-toggle="dropdown" href="#">');
WriteLn('												<i class="fa fa-envelope fa-fw"></i>  <i class="fa fa-caret-down"></i>');
WriteLn('										</a>');
WriteLn('										<ul class="dropdown-menu dropdown-messages">');
WriteLn('												<li>');
WriteLn('														<a href="#">');
WriteLn('																<div>');
WriteLn('																		<strong>John Smith</strong>');
WriteLn('																		<span class="pull-right text-muted">');
WriteLn('																				<em>Yesterday</em>');
WriteLn('																		</span>');
WriteLn('																</div>');
WriteLn('																<div>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque eleifend...</div>');
WriteLn('														</a>');
WriteLn('												</li>');
WriteLn('												<li class="divider"></li>');
WriteLn('												<li>');
WriteLn('														<a href="#">');
WriteLn('																<div>');
WriteLn('																		<strong>John Smith</strong>');
WriteLn('																		<span class="pull-right text-muted">');
WriteLn('																				<em>Yesterday</em>');
WriteLn('																		</span>');
WriteLn('																</div>');
WriteLn('																<div>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque eleifend...</div>');
WriteLn('														</a>');
WriteLn('												</li>');
WriteLn('												<li class="divider"></li>');
WriteLn('												<li>');
WriteLn('														<a href="#">');
WriteLn('																<div>');
WriteLn('																		<strong>John Smith</strong>');
WriteLn('																		<span class="pull-right text-muted">');
WriteLn('																				<em>Yesterday</em>');
WriteLn('																		</span>');
WriteLn('																</div>');
WriteLn('																<div>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque eleifend...</div>');
WriteLn('														</a>');
WriteLn('												</li>');
WriteLn('												<li class="divider"></li>');
WriteLn('												<li>');
WriteLn('														<a class="text-center" href="#">');
WriteLn('																<strong>Read All Messages</strong>');
WriteLn('																<i class="fa fa-angle-right"></i>');
WriteLn('														</a>');
WriteLn('												</li>');
WriteLn('										</ul>');
WriteLn('										<!-- /.dropdown-messages -- >');
WriteLn('								</li-->');
WriteLn('								<!-- /.dropdown -->');
WriteLn('								<!--li class="dropdown">');
WriteLn('										<a class="dropdown-toggle" data-toggle="dropdown" href="#">');
WriteLn('												<i class="fa fa-tasks fa-fw"></i>  <i class="fa fa-caret-down"></i>');
WriteLn('										</a>');
WriteLn('										<ul class="dropdown-menu dropdown-tasks">');
WriteLn('												<li>');
WriteLn('														<a href="#">');
WriteLn('																<div>');
WriteLn('																		<p>');
WriteLn('																				<strong>Task 1</strong>');
WriteLn('																				<span class="pull-right text-muted">40% Complete</span>');
WriteLn('																		</p>');
WriteLn('																		<div class="progress progress-striped active">');
WriteLn('																				<div class="progress-bar progress-bar-success" role="progressbar" aria-valuenow="40" aria-valuemin="0" aria-valuemax="100" style="width: 40%">');
WriteLn('																						<span class="sr-only">40% Complete (success)</span>');
WriteLn('																				</div>');
WriteLn('																		</div>');
WriteLn('																</div>');
WriteLn('														</a>');
WriteLn('												</li>');
WriteLn('												<li class="divider"></li>');
WriteLn('												<li>');
WriteLn('														<a href="#">');
WriteLn('																<div>');
WriteLn('																		<p>');
WriteLn('																				<strong>Task 2</strong>');
WriteLn('																				<span class="pull-right text-muted">20% Complete</span>');
WriteLn('																		</p>');
WriteLn('																		<div class="progress progress-striped active">');
WriteLn('																				<div class="progress-bar progress-bar-info" role="progressbar" aria-valuenow="20" aria-valuemin="0" aria-valuemax="100" style="width: 20%">');
WriteLn('																						<span class="sr-only">20% Complete</span>');
WriteLn('																				</div>');
WriteLn('																		</div>');
WriteLn('																</div>');
WriteLn('														</a>');
WriteLn('												</li>');
WriteLn('												<li class="divider"></li>');
WriteLn('												<li>');
WriteLn('														<a href="#">');
WriteLn('																<div>');
WriteLn('																		<p>');
WriteLn('																				<strong>Task 3</strong>');
WriteLn('																				<span class="pull-right text-muted">60% Complete</span>');
WriteLn('																		</p>');
WriteLn('																		<div class="progress progress-striped active">');
WriteLn('																				<div class="progress-bar progress-bar-warning" role="progressbar" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100" style="width: 60%">');
WriteLn('																						<span class="sr-only">60% Complete (warning)</span>');
WriteLn('																				</div>');
WriteLn('																		</div>');
WriteLn('																</div>');
WriteLn('														</a>');
WriteLn('												</li>');
WriteLn('												<li class="divider"></li>');
WriteLn('												<li>');
WriteLn('														<a href="#">');
WriteLn('																<div>');
WriteLn('																		<p>');
WriteLn('																				<strong>Task 4</strong>');
WriteLn('																				<span class="pull-right text-muted">80% Complete</span>');
WriteLn('																		</p>');
WriteLn('																		<div class="progress progress-striped active">');
WriteLn('																				<div class="progress-bar progress-bar-danger" role="progressbar" aria-valuenow="80" aria-valuemin="0" aria-valuemax="100" style="width: 80%">');
WriteLn('																						<span class="sr-only">80% Complete (danger)</span>');
WriteLn('																				</div>');
WriteLn('																		</div>');
WriteLn('																</div>');
WriteLn('														</a>');
WriteLn('												</li>');
WriteLn('												<li class="divider"></li>');
WriteLn('												<li>');
WriteLn('														<a class="text-center" href="#">');
WriteLn('																<strong>See All Tasks</strong>');
WriteLn('																<i class="fa fa-angle-right"></i>');
WriteLn('														</a>');
WriteLn('												</li>');
WriteLn('										</ul>');
WriteLn('										<!-- /.dropdown-tasks -- >');
WriteLn('								</li-->');
WriteLn('								<!-- /.dropdown -->');
WriteLn('								<!--li class="dropdown">');
WriteLn('										<a class="dropdown-toggle" data-toggle="dropdown" href="#">');
WriteLn('												<i class="fa fa-bell fa-fw"></i>  <i class="fa fa-caret-down"></i>');
WriteLn('										</a>');
WriteLn('										<ul class="dropdown-menu dropdown-alerts">');
WriteLn('												<li>');
WriteLn('														<a href="#">');
WriteLn('																<div>');
WriteLn('																		<i class="fa fa-comment fa-fw"></i> New Comment');
WriteLn('																		<span class="pull-right text-muted small">4 minutes ago</span>');
WriteLn('																</div>');
WriteLn('														</a>');
WriteLn('												</li>');
WriteLn('												<li class="divider"></li>');
WriteLn('												<li>');
WriteLn('														<a href="#">');
WriteLn('																<div>');
WriteLn('																		<i class="fa fa-twitter fa-fw"></i> 3 New Followers');
WriteLn('																		<span class="pull-right text-muted small">12 minutes ago</span>');
WriteLn('																</div>');
WriteLn('														</a>');
WriteLn('												</li>');
WriteLn('												<li class="divider"></li>');
WriteLn('												<li>');
WriteLn('														<a href="#">');
WriteLn('																<div>');
WriteLn('																		<i class="fa fa-envelope fa-fw"></i> Message Sent');
WriteLn('																		<span class="pull-right text-muted small">4 minutes ago</span>');
WriteLn('																</div>');
WriteLn('														</a>');
WriteLn('												</li>');
WriteLn('												<li class="divider"></li>');
WriteLn('												<li>');
WriteLn('														<a href="#">');
WriteLn('																<div>');
WriteLn('																		<i class="fa fa-tasks fa-fw"></i> New Task');
WriteLn('																		<span class="pull-right text-muted small">4 minutes ago</span>');
WriteLn('																</div>');
WriteLn('														</a>');
WriteLn('												</li>');
WriteLn('												<li class="divider"></li>');
WriteLn('												<li>');
WriteLn('														<a href="#">');
WriteLn('																<div>');
WriteLn('																		<i class="fa fa-upload fa-fw"></i> Server Rebooted');
WriteLn('																		<span class="pull-right text-muted small">4 minutes ago</span>');
WriteLn('																</div>');
WriteLn('														</a>');
WriteLn('												</li>');
WriteLn('												<li class="divider"></li>');
WriteLn('												<li>');
WriteLn('														<a class="text-center" href="#">');
WriteLn('																<strong>See All Alerts</strong>');
WriteLn('																<i class="fa fa-angle-right"></i>');
WriteLn('														</a>');
WriteLn('												</li>');
WriteLn('										</ul>');
WriteLn('										<!-- /.dropdown-alerts -- >');
WriteLn('								</li-->');
WriteLn('								<!-- /.dropdown -->');
WriteLn('								<li class="dropdown">');
WriteLn('										<a class="dropdown-toggle" data-toggle="dropdown" href="#">');
WriteLn('												<i class="fa fa-user fa-fw"></i>  <i class="fa fa-caret-down"></i>');
WriteLn('										</a>');
WriteLn('										<ul class="dropdown-menu dropdown-user">');
WriteLn('												<!--li><a href="#"><i class="fa fa-user fa-fw"></i> User Profile</a>');
WriteLn('												</li>');
WriteLn('												<li><a href="#"><i class="fa fa-gear fa-fw"></i> Settings</a>');
WriteLn('												</li>');
WriteLn('												<li class="divider"></li-->');
Write  ('												'); WriteVl(ItemDoMenu(NovaRota.Nome('Padrao').Controlador('Autenticacao').Acao('Sair'), HTMLPuro('<i class="fa fa-sign-out fa-fw"></i> Sair'))); WriteLn('');
WriteLn('										</ul>');
WriteLn('										<!-- /.dropdown-user -->');
WriteLn('								</li>');
WriteLn('								<!-- /.dropdown -->');
WriteLn('						</ul>');
WriteLn('						<!-- /.navbar-top-links -->');
WriteLn('');
WriteLn('						<div class="navbar-default sidebar" role="navigation">');
WriteLn('								<div class="sidebar-nav navbar-collapse">');
WriteLn('										<ul class="nav" id="side-menu">');
WriteLn('												<!--li class="sidebar-search">');
WriteLn('														<div class="input-group custom-search-form">');
WriteLn('																<input type="text" class="form-control" placeholder="Search...">');
WriteLn('																<span class="input-group-btn">');
WriteLn('																		<button class="btn btn-default" type="button">');
WriteLn('																				<i class="fa fa-search"></i>');
WriteLn('																		</button>');
WriteLn('																</span>');
WriteLn('														</div>');
WriteLn('														<!-- /input-group -- >');
WriteLn('												</li-->');
WriteLn('												<li>');
WriteLn('														<a href="index.html"><i class="fa fa-dashboard fa-fw"></i> Dashboard</a>');
WriteLn('												</li>');
WriteLn('												<li>');
WriteLn('														<a href="#"><i class="fa fa-bar-chart-o fa-fw"></i> Charts<span class="fa arrow"></span></a>');
WriteLn('														<ul class="nav nav-second-level">');
WriteLn('																<li>');
WriteLn('																		<a href="flot.html">Flot Charts</a>');
WriteLn('																</li>');
WriteLn('																<li>');
WriteLn('																		<a href="morris.html">Morris.js Charts</a>');
WriteLn('																</li>');
WriteLn('														</ul>');
WriteLn('														<!-- /.nav-second-level -->');
WriteLn('												</li>');
WriteLn('												<li>');
WriteLn('														<a href="tables.html"><i class="fa fa-table fa-fw"></i> Tables</a>');
WriteLn('												</li>');
WriteLn('												<li>');
WriteLn('														<a href="forms.html"><i class="fa fa-edit fa-fw"></i> Forms</a>');
WriteLn('												</li>');
WriteLn('												<li>');
WriteLn('														<a href="#"><i class="fa fa-wrench fa-fw"></i> UI Elements<span class="fa arrow"></span></a>');
WriteLn('														<ul class="nav nav-second-level">');
WriteLn('																<li>');
WriteLn('																		<a href="panels-wells.html">Panels and Wells</a>');
WriteLn('																</li>');
WriteLn('																<li>');
WriteLn('																		<a href="buttons.html">Buttons</a>');
WriteLn('																</li>');
WriteLn('																<li>');
WriteLn('																		<a href="notifications.html">Notifications</a>');
WriteLn('																</li>');
WriteLn('																<li>');
WriteLn('																		<a href="typography.html">Typography</a>');
WriteLn('																</li>');
WriteLn('																<li>');
WriteLn('																		<a href="icons.html"> Icons</a>');
WriteLn('																</li>');
WriteLn('																<li>');
WriteLn('																		<a href="grid.html">Grid</a>');
WriteLn('																</li>');
WriteLn('														</ul>');
WriteLn('														<!-- /.nav-second-level -->');
WriteLn('												</li>');
WriteLn('												<li>');
WriteLn('														<a href="#"><i class="fa fa-sitemap fa-fw"></i> Multi-Level Dropdown<span class="fa arrow"></span></a>');
WriteLn('														<ul class="nav nav-second-level">');
WriteLn('																<li>');
WriteLn('																		<a href="#">Second Level Item</a>');
WriteLn('																</li>');
WriteLn('																<li>');
WriteLn('																		<a href="#">Second Level Item</a>');
WriteLn('																</li>');
WriteLn('																<li>');
WriteLn('																		<a href="#">Third Level <span class="fa arrow"></span></a>');
WriteLn('																		<ul class="nav nav-third-level">');
WriteLn('																				<li>');
WriteLn('																						<a href="#">Third Level Item</a>');
WriteLn('																				</li>');
WriteLn('																				<li>');
WriteLn('																						<a href="#">Third Level Item</a>');
WriteLn('																				</li>');
WriteLn('																				<li>');
WriteLn('																						<a href="#">Third Level Item</a>');
WriteLn('																				</li>');
WriteLn('																				<li>');
WriteLn('																						<a href="#">Third Level Item</a>');
WriteLn('																				</li>');
WriteLn('																		</ul>');
WriteLn('																		<!-- /.nav-third-level -->');
WriteLn('																</li>');
WriteLn('														</ul>');
WriteLn('														<!-- /.nav-second-level -->');
WriteLn('												</li>');
WriteLn('												<li class="active">');
WriteLn('														<a href="#"><i class="fa fa-files-o fa-fw"></i> Sample Pages<span class="fa arrow"></span></a>');
WriteLn('														<ul class="nav nav-second-level">');
WriteLn('																<li>');
WriteLn('																		<a class="active" href="blank.html">Blank Page</a>');
WriteLn('																</li>');
WriteLn('																<li>');
WriteLn('																		<a href="login.html">Login Page</a>');
WriteLn('																</li>');
WriteLn('														</ul>');
WriteLn('														<!-- /.nav-second-level -->');
WriteLn('												</li>');
WriteLn('										</ul>');
WriteLn('								</div>');
WriteLn('								<!-- /.sidebar-collapse -->');
WriteLn('						</div>');
WriteLn('						<!-- /.navbar-static-side -->');
WriteLn('				</nav>');
WriteLn('');
WriteLn('				<!-- Page Content -->');
WriteLn('				<div id="page-wrapper">');
WriteLn('						<div class="container-fluid">');
WriteLn('								<div class="row">');
WriteLn('										<div class="col-lg-12">');
WriteLn('												<h1 class="page-header">Blank</h1>');
Html; WriteLn('');
WriteLn('										</div>');
WriteLn('										<!-- /.col-lg-12 -->');
WriteLn('								</div>');
WriteLn('								<!-- /.row -->');
WriteLn('						</div>');
WriteLn('						<!-- /.container-fluid -->');
WriteLn('				</div>');
WriteLn('				<!-- /#page-wrapper -->');
WriteLn('');
WriteLn('		</div>');
WriteLn('		<!-- /#wrapper -->');
WriteLn('');
Write  ('		'); WriteVl(RecursoJS('jquery')); WriteLn('');
Write  ('		'); WriteVl(RecursoJS('bootstrap')); WriteLn('');
Write  ('		'); WriteVl(RecursoJS('metisMenu')); WriteLn('');
Write  ('		'); WriteVl(RecursoJS('sb-admin-2')); WriteLn('');
Write  ('		'); WriteVl(RecursoJS('ie10-viewport-bug-workaround')); WriteLn('');
WriteLn('	</body>');
Write  ('</html>'); 
end;

function TVisaoPaginaMestra.ItemDoMenu(const ARotaFluente: IRotaFluente; const ACaption: string): IHTMLFluente;
begin
	Result := HTMLFluente('li').SetDentro(Acao(ARotaFluente, ACaption));
	if ARotaFluente.RotaSimilar(Rota) then
		Result.AddClasse('active');
end;

function TVisaoPaginaMestra.ItemDoMenu(const ARotaFluente: IRotaFluente; const AHTMLPuro: THTMLPuro): IHTMLFluente;
begin
	Result := HTMLFluente('li').SetDentro(Acao(ARotaFluente, AHTMLPuro));
	if ARotaFluente.RotaSimilar(Rota) then
		Result.AddClasse('active');
end;

end.